# Generated by Django 2.1.5 on 2019-10-20 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_total', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.PositiveIntegerField()),
                ('genero', models.CharField(max_length=30)),
                ('autor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material_Aprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('dificultad', models.PositiveIntegerField()),
                ('tema', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Minigame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ubicacion', models.FilePathField()),
                ('Solucion', models.FilePathField()),
                ('Evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Ninhos.Evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Ninho',
            fields=[
                ('DNI', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('P_Nombre', models.CharField(max_length=20)),
                ('S_Nombre', models.CharField(max_length=20)),
                ('Apellido_P', models.CharField(max_length=20)),
                ('Apellido_M', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('temas_interes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Preguntas', models.FilePathField()),
                ('Respuestas', models.FilePathField()),
                ('Evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Ninhos.Evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('nivel_lectura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ninho', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Ninhos.Ninho')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField()),
                ('duracion', models.DurationField()),
                ('Material_Aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ninhos.Material_Aprendizaje')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='Material_Apren',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ninhos.Material_Aprendizaje'),
        ),
        migrations.AddField(
            model_name='historial',
            name='material_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Ninhos.Material_Aprendizaje'),
        ),
        migrations.AddField(
            model_name='historial',
            name='ninho',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Ninhos.Ninho'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='Material_A',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ninhos.Material_Aprendizaje'),
        ),
    ]
