# Generated by Django 2.1.5 on 2019-11-24 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ninhos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=2)),
                ('fecha_realizada', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.PositiveIntegerField()),
                ('genero', models.CharField(max_length=30)),
                ('autor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material_Aprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=60)),
                ('dificultad', models.PositiveIntegerField()),
                ('imagen', models.FilePathField()),
                ('tema', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ninho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_Nombre', models.CharField(max_length=20)),
                ('S_Nombre', models.CharField(max_length=20)),
                ('Apellido_P', models.CharField(max_length=20)),
                ('Apellido_M', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('edad_mental', models.PositiveIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('temas_interes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Preguntas', models.FilePathField()),
                ('Respuestas', models.FilePathField()),
                ('Evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Ninhos.Material_Aprendizaje')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('nivel_lectura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ninho', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Ninhos.Ninho')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField()),
                ('duracion', models.DurationField()),
                ('Material_Aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ninhos.Material_Aprendizaje')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='Material_Apren',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ninhos.Material_Aprendizaje'),
        ),
        migrations.AddField(
            model_name='historial',
            name='material_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Ninhos.Material_Aprendizaje'),
        ),
        migrations.AddField(
            model_name='historial',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Ninhos.Usuario'),
        ),
    ]
