# Generated by Django 2.1.5 on 2019-12-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ninhos', '0002_auto_20191128_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_aprendizaje',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
