# Generated by Django 2.1.5 on 2019-12-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ninhos', '0003_auto_20191205_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_aprendizaje',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
