# Generated by Django 2.1.5 on 2019-12-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ninhos', '0004_auto_20191205_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_aprendizaje',
            name='imagen',
            field=models.ImageField(upload_to='Ninhos/static/Imagenes_BD/'),
        ),
    ]
